version: "3"

services:
  drone-db:
    image: postgres:16.0
    container_name: drone_db
    # restart: always
    networks:
      - drone-network # 加入到drone网络
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=drone # PGSQL默认用户
      - POSTGRES_PASSWORD=drone # PGSQL默认密码
      - POSTGRES_DB=drone # PGSQL默认数据库
    volumes:
      - ./drone-db:/var/lib/postgresql/data
  drone-server:
    image: drone/drone:2.11
    container_name: drone
    ports:
      - 10081:80
      - 9000
    volumes:
      - ./drone:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_OPEN=true
      # - DRONE_SERVER_HOST=drone-server
      - DRONE_SERVER_HOST=localhost:10081
      - DRONE_SERVER_PROTO=http
      - DRONE_LOGS_TRACE=true
      - DRONE_LOGS_DEBUG=true
      # - DRONE_GITEA_SERVER=http://localhost:13000
      - DRONE_GITEA_SKIP_VERIFY=true
      - DRONE_GITEA_SERVER=http://host.docker.internal:13000
      - DRONE_GITEA_CLIENT_ID=dd34f47a-57cf-417e-8a4d-b4accc08377a
      - DRONE_GITEA_CLIENT_SECRET=gto_pfvareujq5l2644wfnajsmahgubrsw4ddg26kuxbosmwfiezgo6a
      - DRONE_PROVIDER=gitea
      #- DRONE_DATABASE_DATASOURCE=/var/lib/drone/drone.sqlite
      #- DRONE_DATABASE_DRIVER=sqlite3
      - DRONE_DATABASE_DRIVER=postgres # 数据库类型
      - DRONE_DATABASE_DATASOURCE=postgres://drone:drone@drone-db/drone?sslmode=disable # 数据库连接
      - DRONE_RPC_SECRET=MWckgvhjqg4E3eQ0psgZX4iNCxoQiyU4LLvO4eXFFuHtrTkIy8vwcAc3erB5f9reM
      - DRONE_SECRET=ALQU2M0KdptXUdTPKcEw
      - DRONE_USER_CREATE=username:daming,admin:true
    networks:
      - drone-network
  drone-runner-docker:
    image: drone/drone-runner-docker:1.8.1
    depends_on:
      - drone-server
    volumes:
      - ./tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - ./pipe/docker_engine://./pipe/docker_engine
    restart: always
    ports:
      - 13001:3000
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=MWckgvhjqg4E3eQ0psgZX4iNCxoQiyU4LLvO4eXFFuHtrTkIy8vwcAc3erB5f9reM
      - DRONE_LOGS_TRACE=true
      - DRONE_LOGS_DEBUG=true
      - DRONE_RUNNER_CAPCAITY=2
      - DRONE_RUNNER_NAME=docker-runner
      - DRONE_SECRET=ALQU2M0KdptXUdTPKcEw
    networks:
      - drone-network

networks:
  drone-network:
    external: false